apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv_registry
  labels:
    name: registry
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.1.3
    path: /USBDisk1/registry

