apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv_registry
  labels:
    name: registry
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: {{ nfs_server_address }}
    path: {{ nfs_path }}

